blank_issues_enabled: false
contact_links:
  - name: Support Request / General Question â“
    url: https://github.com/bit-team/backintime/issues/new
    about: This redirects you to the Issue section of the main repository "backintime".
